# Data Preprocessing
This notebook aims to perform data preprocessing on the original dataset.

In [23]:
!pip install -qqq unidecode contractions pyspellchecker wordninja symspellpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 541.6/541.6 kB 14.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 25.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 108.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 104.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.3/168.3 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 35.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.7 MB/s eta 0:00:00
  Building wheel for wordninja (setup.py) ... done

In [24]:
import os
import pandas as pd
import numpy as np
import spacy
import unidecode
import contractions as contract
import re
import wordninja
import collections
import pkg_resources
from spellchecker import SpellChecker
from symspellpy import SymSpell, Verbosity

/tmp/ipykernel_3864/720208522.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [25]:
#Downloading NLTK Resources
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [14]:
import os
os.listdir()

['.config', '.ipynb_checkpoints', 'Suicide_Detection.csv', 'sample_data']

In [19]:
#loading dataset
import pandas as pd

df = pd.read_csv(
    "Suicide_Detection.csv",
    encoding='utf-8',
    engine='python',
    on_bad_lines='skip'
)

In [20]:
df.head()

  Unnamed: 0                                               text        class
0          2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1          3  Am I weird I don't get affected by compliments...  non-suicide
2          4  Finally 2020 is almost over... So I can never ...  non-suicide
3          8          i need helpjust help me im crying so hard      suicide
4          9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [30]:
# Defining methods

nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
vocab = collections.Counter()
sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt")
bigram_path = pkg_resources.resource_filename(
"symspellpy", "frequency_bigramdictionary_en_243_342.txt")
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)
sym_spell.load_bigram_dictionary(bigram_path, term_index=0, count_index=2)

# Spell Check using Symspell
def fix_spelling(text):
    suggestions = sym_spell.lookup_compound(text, max_edit_distance=2)
    correctedtext = suggestions[0].term # get the first suggestion, otherwise returns original text if nothing is corrected
    return correctedtext

# Remove some important words from stopwords list
deselect_stop_words = ['no', 'not']

for w in deselect_stop_words:
    nlp.vocab[w].is_stop = False

# Remove extra whitespaces from text
def remove_whitespace(text):
    text = text.strip()
    return " ".join(text.split())

# Remove accented characters from text, e.g. café
def remove_accented_chars(text):
    text = unidecode.unidecode(text)
    return text

# Remove URL
def remove_url(text):
    return re.sub(r'http\S+', '', text)

# Removing symbols and digits
def remove_symbols_digits(text):
    return re.sub('[^a-zA-Z\s]', ' ', text)

# Removing special characters
def remove_special(text):
    return text.replace("\r", " ").replace("\n", " ").replace("    ", " ").replace('"', '')

# Fix word lengthening (characters are wrongly repeated)
def fix_lengthening(text):
    pattern = re.compile(r"(.)\1{2,}")
    return pattern.sub(r"\1\1", text)

def text_preprocessing(text, accented_chars=True, contractions=True, convert_num=True,
                       extra_whitespace=True, lemmatization=True, lowercase=True,
                       url=True, symbols_digits=True, special_chars=True,
                       stop_words=True, lengthening=True, spelling=True):
    """preprocess text with default option set to true for all steps"""
    if accented_chars == True: # remove accented characters
        text = remove_accented_chars(text)
    if contractions == True: # expand contractions
        text = contract.fix(text)
    if lowercase == True: # convert all characters to lowercase
        text = text.lower()
    if url == True: # remove URLs before removing symbols
        text = remove_url(text)
    if symbols_digits == True: # remove symbols and digits
        text = remove_symbols_digits(text)
    if special_chars == True: # remove special characters
        text = remove_special(text)
    if extra_whitespace == True: # remove extra whitespaces
        text = remove_whitespace(text)
    if lengthening == True: # fix word lengthening
        text = fix_lengthening(text)
    if spelling == True: # fix spelling
        text = fix_spelling(text)

    doc = nlp(text) # tokenise text

    clean_text = []

    # return text

    for token in doc:
        flag = True
        edit = token.text
        # remove stop words
        if stop_words == True and token.is_stop and token.pos_ != 'NUM':
            flag = False
        # exclude number words
        if convert_num == True and token.pos_ == 'NUM' and flag == True:
            flag = False
        # convert tokens to base form
        elif lemmatization == True and token.lemma_ != "-PRON-" and flag == True:
            edit = token.lemma_
        # append tokens edited and not removed to list
        if edit != "" and flag == True:
            clean_text.append(edit)
    return " ".join(clean_text)

<>:41: SyntaxWarning: invalid escape sequence '\s'
<>:41: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3864/309113051.py:41: SyntaxWarning: invalid escape sequence '\s'
  return re.sub('[^a-zA-Z\s]', ' ', text)

In [27]:
# Test functions on a subset of 20 rows
df['cleaned_text'] = df['text'][:20].apply(lambda row: text_preprocessing(row))
df[:20]

,Unnamed: 0,text,class,cleaned_text
0,2,Ex Wife Threatening SuicideRecently I left my ...,suicide,sex wife threaten suicide recently leave wife ...
1,3,Am I weird I don't get affected by compliments...,non-suicide,weird not affect compliment come know girl fee...
2,4,Finally 2020 is almost over... So I can never ...,non-suicide,finally hear bad year swear fuck god annoying
3,8,i need helpjust help me im crying so hard,suicide,need help help cry hard
4,9,"I’m so lostHello, my name is Adam (16) and I’v...",suicide,lose hello adam struggle year afraid past year...
5,11,Honetly idkI dont know what im even doing here...,suicide,honestly d not know feel like feel unbearably ...
6,12,[Trigger warning] Excuse for self inflicted bu...,suicide,trigger warn excuse self inflict burn know cri...
7,13,It ends tonight.I can’t do it anymore. \nI quit.,suicide,end tonight not anymore quit
8,16,"Everyone wants to be ""edgy"" and it's making me...",non-suicide,want edgy make self conscious feel like not st...
9,18,My life is over at 20 years oldHello all. I am...,suicide,life year old hello year old balding male hair...
10,19,I took the rest of my sleeping pills and my pa...,suicide,take rest sleeping pill painkiller not wait en...
11,20,Can you imagine getting old? Me neither.Wrinkl...,suicide,imagine get old wrinkles weight gain hair loss...
12,21,Do you think getting hit by a train would be p...,suicide,think getting hit train painful gun hard come ...
13,22,"death, continuedI posted here before and saw s...",suicide,death continue post see interesting ask inform...
14,23,Been arrested - feeling suicidalEdit,suicide,arrest feel suicidal edit
15,24,Fuck the verizon smart family app I can’t even...,non-suicide,fuck verizon smart family app not watch porn p...
16,25,I’m scared. Everything just seems to be gett...,suicide,scared get bad bad young think transgend not s...
17,26,"Well, Im screwed. I locked myself in the schoo...",non-suicide,screw lock school toilet not edit live tell story
18,27,I'm fucked assignment is due tomorrow and I ha...,non-suicide,fuck assignment tomorrow not start
19,29,yeaputting a knife to my wrist didn't give me ...,suicide,yea put knife wrist not hesitation like free f...

In [29]:
df = df.sample(20000, random_state=42)

In [32]:
df['text'] = df['text'].fillna('')

In [33]:
from tqdm import tqdm
tqdm.pandas()

df['cleaned_text'] = df['text'].progress_apply(text_preprocessing)

100%|██████████| 20000/20000 [09:14<00:00, 36.04it/s]

In [34]:
# Export cleaned dataset
# df.to_csv('Data/suicide_detection_full_cleaned.csv', index=False)

df.to_csv('suicide_detection_full_cleaned.csv', index=False)